"""Rescue task registry and contract surfaces."""

from scz_target_engine.rescue.contracts import (
    RESCUE_TASK_CONTRACT_ARTIFACT_NAME,
    RescueArtifactContract,
    RescueLeakageBoundary,
    RescueTaskContract,
    read_rescue_task_contract,
)
from scz_target_engine.rescue.frozen import (
    FrozenRescueDataset,
    FrozenRescueGovernedTaskBundle,
    FrozenRescueTaskBundle,
    load_frozen_rescue_governance_bundle,
    load_frozen_rescue_task_bundle,
)
from scz_target_engine.rescue.governance import (
    RESCUE_DATASET_CARD_ARTIFACT_NAME,
    RESCUE_FREEZE_MANIFEST_ARTIFACT_NAME,
    RESCUE_RAW_TO_FROZEN_LINEAGE_ARTIFACT_NAME,
    RESCUE_SPLIT_MANIFEST_ARTIFACT_NAME,
    RESCUE_TASK_CARD_ARTIFACT_NAME,
    RescueDatasetCard,
    RescueFreezeManifest,
    RescueGovernanceBundle,
    RescueRawToFrozenLineage,
    RescueSplitManifest,
    RescueTaskCard,
    read_rescue_dataset_card,
    read_rescue_freeze_manifest,
    read_rescue_raw_to_frozen_lineage,
    read_rescue_split_manifest,
    read_rescue_task_card,
    validate_rescue_governance_bundle,
)
from scz_target_engine.rescue.glutamatergic_convergence import (
    GLUTAMATERGIC_CONVERGENCE_ATLAS_FIXTURE_MANIFEST_PATH,
    GLUTAMATERGIC_CONVERGENCE_EVALUATION_LABELS_PATH,
    GLUTAMATERGIC_CONVERGENCE_RAW_CONVERGENCE_MANIFEST_PATH,
    GLUTAMATERGIC_CONVERGENCE_RAW_SNAPSHOT_MANIFEST_PATH,
    GLUTAMATERGIC_CONVERGENCE_RAW_TENSOR_MANIFEST_PATH,
    GLUTAMATERGIC_CONVERGENCE_RANKING_INPUTS_PATH,
    GLUTAMATERGIC_CONVERGENCE_TASK_CARD_PATH,
    GlutamatergicConvergenceRawSnapshotBundle,
    GlutamatergicConvergenceRescueBundle,
    load_glutamatergic_convergence_rescue_bundle,
    validate_glutamatergic_convergence_raw_snapshot_bundle,
)
from scz_target_engine.rescue.tasks import (
    DEFAULT_GLUTAMATERGIC_CONVERGENCE_BASELINE_ID,
    DEFAULT_GLUTAMATERGIC_CONVERGENCE_TASK_ID,
    DEFAULT_INTERNEURON_BASELINE_IDS,
    DEFAULT_NPC_SIGNATURE_REVERSAL_SCORERS,
    INTERNEURON_ARBOR_AXIS_ID,
    INTERNEURON_SYNAPSE_AXIS_ID,
    INTERNEURON_TASK_CARD_PATH,
    INTERNEURON_TASK_ID,
    NPC_SIGNATURE_REVERSAL_PRIMARY_SCORER_ID,
    NPC_SIGNATURE_REVERSAL_TASK_ID,
    NPC_SIGNATURE_REVERSAL_TASK_LABEL,
    NpcSignatureReversalScorerDefinition,
    VALID_INTERNEURON_AXIS_IDS,
    build_glutamatergic_convergence_ranked_predictions,
    build_interneuron_axis_predictions,
    evaluate_glutamatergic_convergence_ranked_predictions,
    evaluate_interneuron_axis_predictions,
    list_interneuron_baselines,
    load_glutamatergic_convergence_rescue_task_bundle,
    load_interneuron_arbor_task_data,
    load_interneuron_axis_task_data,
    load_interneuron_synapse_task_data,
    materialize_glutamatergic_convergence_rescue_evaluation,
    materialize_interneuron_arbor_rescue_runs,
    materialize_interneuron_axis_rescue_runs,
    materialize_interneuron_rescue_lane,
    materialize_interneuron_synapse_rescue_runs,
    materialize_npc_signature_reversal_run,
    resolve_interneuron_baseline,
)

__all__ = [
    "DEFAULT_RESCUE_TASK_REGISTRY_PATH",
    "DEFAULT_NPC_SIGNATURE_REVERSAL_SCORERS",
    "NPC_SIGNATURE_REVERSAL_PRIMARY_SCORER_ID",
    "GLUTAMATERGIC_CONVERGENCE_ATLAS_FIXTURE_MANIFEST_PATH",
    "GLUTAMATERGIC_CONVERGENCE_EVALUATION_LABELS_PATH",
    "GLUTAMATERGIC_CONVERGENCE_RAW_CONVERGENCE_MANIFEST_PATH",
    "GLUTAMATERGIC_CONVERGENCE_RAW_SNAPSHOT_MANIFEST_PATH",
    "GLUTAMATERGIC_CONVERGENCE_RAW_TENSOR_MANIFEST_PATH",
    "GLUTAMATERGIC_CONVERGENCE_RANKING_INPUTS_PATH",
    "GLUTAMATERGIC_CONVERGENCE_TASK_CARD_PATH",
    "DEFAULT_GLUTAMATERGIC_CONVERGENCE_BASELINE_ID",
    "DEFAULT_GLUTAMATERGIC_CONVERGENCE_TASK_ID",
    "DEFAULT_INTERNEURON_BASELINE_IDS",
    "INTERNEURON_ARBOR_AXIS_ID",
    "INTERNEURON_SYNAPSE_AXIS_ID",
    "INTERNEURON_TASK_CARD_PATH",
    "INTERNEURON_TASK_ID",
    "VALID_INTERNEURON_AXIS_IDS",
    "NPC_SIGNATURE_REVERSAL_TASK_ID",
    "NPC_SIGNATURE_REVERSAL_TASK_LABEL",
    "FrozenRescueDataset",
    "FrozenRescueGovernedTaskBundle",
    "FrozenRescueTaskBundle",
    "RESCUE_DATASET_CARD_ARTIFACT_NAME",
    "RESCUE_FREEZE_MANIFEST_ARTIFACT_NAME",
    "RESCUE_RAW_TO_FROZEN_LINEAGE_ARTIFACT_NAME",
    "RESCUE_SPLIT_MANIFEST_ARTIFACT_NAME",
    "RESCUE_TASK_CONTRACT_ARTIFACT_NAME",
    "RESCUE_TASK_CARD_ARTIFACT_NAME",
    "GlutamatergicConvergenceRawSnapshotBundle",
    "GlutamatergicConvergenceRescueBundle",
    "NpcSignatureReversalScorerDefinition",
    "RescueArtifactContract",
    "RescueDatasetCard",
    "RescueFreezeManifest",
    "RescueGovernanceBundle",
    "RescueLeakageBoundary",
    "RescueRawToFrozenLineage",
    "RescueSplitManifest",
    "RescueSuiteContract",
    "RescueTaskContract",
    "RescueTaskCard",
    "RescueTaskRegistration",
    "read_rescue_dataset_card",
    "read_rescue_freeze_manifest",
    "read_rescue_raw_to_frozen_lineage",
    "read_rescue_split_manifest",
    "load_rescue_suite_contracts",
    "load_rescue_task_contracts",
    "load_rescue_task_registrations",
    "build_interneuron_axis_predictions",
    "evaluate_interneuron_axis_predictions",
    "list_interneuron_baselines",
    "build_glutamatergic_convergence_ranked_predictions",
    "evaluate_glutamatergic_convergence_ranked_predictions",
    "load_glutamatergic_convergence_rescue_bundle",
    "load_frozen_rescue_governance_bundle",
    "load_glutamatergic_convergence_rescue_task_bundle",
    "materialize_glutamatergic_convergence_rescue_evaluation",
    "validate_glutamatergic_convergence_raw_snapshot_bundle",
    "load_interneuron_arbor_task_data",
    "load_interneuron_axis_task_data",
    "load_interneuron_synapse_task_data",
    "load_frozen_rescue_task_bundle",
    "materialize_interneuron_arbor_rescue_runs",
    "materialize_interneuron_axis_rescue_runs",
    "materialize_interneuron_rescue_lane",
    "materialize_interneuron_synapse_rescue_runs",
    "materialize_npc_signature_reversal_run",
    "read_rescue_task_contract",
    "read_rescue_task_card",
    "resolve_interneuron_baseline",
    "resolve_rescue_suite_contract",
    "resolve_rescue_task_contract",
    "validate_rescue_governance_bundle",
]


def __getattr__(name: str) -> object:
    if name in {
        "DEFAULT_RESCUE_TASK_REGISTRY_PATH",
        "RescueSuiteContract",
        "RescueTaskRegistration",
        "load_rescue_suite_contracts",
        "load_rescue_task_contracts",
        "load_rescue_task_registrations",
        "resolve_rescue_suite_contract",
        "resolve_rescue_task_contract",
    }:
        from scz_target_engine.rescue.registry import (
            DEFAULT_RESCUE_TASK_REGISTRY_PATH,
            RescueSuiteContract,
            RescueTaskRegistration,
            load_rescue_suite_contracts,
            load_rescue_task_contracts,
            load_rescue_task_registrations,
            resolve_rescue_suite_contract,
            resolve_rescue_task_contract,
        )

        return {
            "DEFAULT_RESCUE_TASK_REGISTRY_PATH": DEFAULT_RESCUE_TASK_REGISTRY_PATH,
            "RescueSuiteContract": RescueSuiteContract,
            "RescueTaskRegistration": RescueTaskRegistration,
            "load_rescue_suite_contracts": load_rescue_suite_contracts,
            "load_rescue_task_contracts": load_rescue_task_contracts,
            "load_rescue_task_registrations": load_rescue_task_registrations,
            "resolve_rescue_suite_contract": resolve_rescue_suite_contract,
            "resolve_rescue_task_contract": resolve_rescue_task_contract,
        }[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
